// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	database "github.com/kirill010106/multibank_service_app/backend/internal/database"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// MockDBInterface is an autogenerated mock type for the DBInterface type
type MockDBInterface struct {
	mock.Mock
}

type MockDBInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBInterface) EXPECT() *MockDBInterface_Expecter {
	return &MockDBInterface_Expecter{mock: &_m.Mock}
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *MockDBInterface) ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (sql.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) sql.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBInterface_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockDBInterface_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *MockDBInterface_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *MockDBInterface_ExecContext_Call {
	return &MockDBInterface_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDBInterface_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...interface{})) *MockDBInterface_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDBInterface_ExecContext_Call) Return(_a0 sql.Result, _a1 error) *MockDBInterface_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBInterface_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (sql.Result, error)) *MockDBInterface_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function with given fields: ctx, query, args
func (_m *MockDBInterface) QueryRowContext(ctx context.Context, query string, args ...interface{}) database.RowScanner {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 database.RowScanner
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) database.RowScanner); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.RowScanner)
		}
	}

	return r0
}

// MockDBInterface_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type MockDBInterface_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *MockDBInterface_Expecter) QueryRowContext(ctx interface{}, query interface{}, args ...interface{}) *MockDBInterface_QueryRowContext_Call {
	return &MockDBInterface_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDBInterface_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...interface{})) *MockDBInterface_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDBInterface_QueryRowContext_Call) Return(_a0 database.RowScanner) *MockDBInterface_QueryRowContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBInterface_QueryRowContext_Call) RunAndReturn(run func(context.Context, string, ...interface{}) database.RowScanner) *MockDBInterface_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBInterface creates a new instance of MockDBInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBInterface {
	mock := &MockDBInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
